name: GitHub Actions Demo
run-name: ${{ github.actor }} is releasing the library
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x # Run with latest stable Deno.
      - run: deno fmt --check --ignore=dist --ignore=dist,examples,release.config.js,*.md,*.json
      - run: deno lint --ignore=dist,examples,release.config.js,*.md,*.json
      - run: deno test
      - name: Semantic Release
        uses: mechanoid/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
